baseURL: "https://0124xt.github.io/Xintian/" 
title: Xintian Wang
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: research/
          weight: 5 
        - name: Publications
          url: publications/
          weight: 2
        - name: CV
          url: cv/
          weight: 4
        - name: Misc
          url: about/
          weight: 3
 

params:
    description: "Welcome to Xintian's personal website."
    author: Xintian Wang
    DateFormat: "June 2025"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["research", "publications", "cv", "about"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Xintian Wang
          subtitle: >
            Hi! I am currently studying Cognitive Neuroscience with a minor in Biology at Washington University in St. Louis.<br>
            Here at WashU, I am working with <a href="https://www.mir.wustl.edu/employees/muriah-wheelock/">Dr. Muriah Wheelock</a> to explore developmental aspects of brain co-fluctuation events using neuroimaging methods.<br>
            I am also working with <a href="https://psych.wustl.edu/people/wouter-kool">Dr. Wouter Kool</a> and Cathy Zhang, using computational modeling to gain insights in the underlying mechanisms of mind-wandering.
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
          - name: Research
            url: research/
          - name: Publications
            url: publications/
          - name: CV
            url: cv/
          - name: Misc
            url: about/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:w.xintian@wustl.edu
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=BwTDE6YAAAAJ&hl=en
        - name: Bluesky
          url: https://bsky.app/profile/xintianw.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Xintian Wang"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2